name: CD - Deploy
on:
    push:
        branches: [ "main" ]



jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 21

            - name: Cache Gradle dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.gradle/caches
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'gradle/libs.versions.toml') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-

            - name: Build JAR
              run: ./gradlew bootJar

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-central-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build and tag Docker image
              run: |
                  docker build -t divarak-service:${{ github.sha }} .
                  docker tag divarak-service:${{ github.sha }} 596484148546.dkr.ecr.eu-central-1.amazonaws.com/divarak/divarak-service:${{ github.sha }}

            - name: Push docker image to ECR
              run: docker push 596484148546.dkr.ecr.eu-central-1.amazonaws.com/divarak/divarak-service:${{ github.sha }}

            - name: Deploy to EC2
              uses: appleboy/ssh-action@v1.2.0
              with:
                  key: ${{ secrets.EC2_SSH_KEY }}
                  username: ubuntu
                  host: ${{ secrets.EC2_HOST }}
                  script: |
                      aws ecr get-login-password --region eu-central-1 \
                        | docker login --username AWS --password-stdin 596484148546.dkr.ecr.eu-central-1.amazonaws.com

                      docker pull 596484148546.dkr.ecr.eu-central-1.amazonaws.com/divarak/divarak-service:${{ github.sha }}

                      docker rm -f divarak-service || true

                      docker images 596484148546.dkr.ecr.eu-central-1.amazonaws.com/divarak --format "{{.ID}}" \
                        | xargs -r docker rmi -f

                      docker run -d --name divarak-service \
                        -p 8080:8080 \
                        -e SPRING_DATASOURCE_URL=${{ secrets.RDS_HOST }}
                        -e SPRING_DATASOURCE_USERNAME=${{ secrets.RDS_USER }}
                        -e SPRING_DATASOURCE_PASSWORD=${{ secrets.RDS_PASSWORD }}
                        596484148546.dkr.ecr.eu-central-1.amazonaws.com/divarak/divarak-service:${{ github.sha }}
